env: "local"
storage_path:  "host=${DB_HOST} port=${DB_PORT} user=${DB_USER} password=${DB_PASS} dbname=${DB_NAME} sslmode=${DB_SSLMODE}"
http_server:
    address: "0.0.0.0:8000"
    timeout: 10s
    idle_timeout: 60s

