env: "local" # local, dev, prod
storage_path:  "host=${DB_HOST} port=${DB_PORT} user=${DB_USER} password=${DB_PASS} dbname=${DB_NAME} sslmode=${DB_SSLMODE}"
http_server:
    address: "localhost:8080"
    timeout: 4s
    idle_timeout: 60s
admin:
    username: "user"
    password: "pa$$"
